services:
  - type: web
    name: pokedex-ci-cd
    runtime: node
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20
    healthCheckPath: /health